### ISSUE TITLE
Proœmium style standardization

### ISSUE THREAD

**Issue by xmarteo** [MRoth1910/Vesperale-Romanum#17]
It sometimes says "we will do...", especially when referencing work that is actually not done yet but will be done before publishing, and sometimes it says "we do...", especially when referencing work that is already done. Unless the proœmium is used to track the advancement of the typesetting, these would be clearer if they were all in present tense, wouldn't they?

**Comment by MRoth1910** [comment]
see 284bfc4364abeb12accd576887acfb067dc3795f

It all makes sense to me as a native speaker, and I don't want to overcommit, but it also seems like I should commit to what I want and then revise if something like the ancient hymns (a bit tedious to typeset even if I greatly simplify it) is not feasible in the end.
